baseURL = "https://mybuntu.github.io/kezosite/"
languageCode = "fr"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
title = "KezoSite"
theme = "blowfish"

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
    contentDir = "content/fr"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"

[menu]
  [[menu.main]]
  name = "Accueil"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "À propos"
  url = "/about/"
  weight = 2

  [[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 3
