baseURL = "https://mybuntu.github.io/kezosite/"
languageCode = "fr"
#defaultContentLanguage = "fr"
#defaultContentLanguageInSubdir = true
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
hasCJKLanguage = false
title = "KezoSite"
theme = "blowfish"

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
    contentDir = "content/fr"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
# Menus FR
[languages.fr.menu]

  [[languages.fr.menu.main]]
  name = "Accueil"
  pageRef = "/"          # racine FR
  weight = 1

  [[languages.fr.menu.main]]
  name = "À propos"
  pageRef = "about"      # content/fr/about.md
  weight = 2

  [[languages.fr.menu.main]]
  name = "Contact"
  pageRef = "contact"    # content/fr/contact.md
  weight = 3


# Menus EN
[languages.en.menu]

  [[languages.en.menu.main]]
  name = "Home"
  pageRef = "/"          # racine EN
  weight = 1

  [[languages.en.menu.main]]
  name = "About"
  pageRef = "about"      # content/en/about.md
  weight = 2

  [[languages.en.menu.main]]
  name = "Contact"
  pageRef = "contact"    # content/en/contact.md
  weight = 3