baseURL = "https://mybuntu.github.io/kezosite/"
languageCode = "fr"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
hasCJKLanguage = false
title = "KezoSite"
theme = "blowfish"

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
    contentDir = "content/fr"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"

## Menus FR
[languages.fr.menu]

  [[languages.fr.menu.main]]
  name = "Accueil"
  pageRef = "/"          # racine FR
  weight = 1

  [[languages.fr.menu.main]]
  name = "À propos"
  pageRef = "about"      # content/fr/about.md
  weight = 2

  [[languages.fr.menu.main]]
  name = "Contact"
  pageRef = "contact"    # content/fr/contact.md
  weight = 3

  [[languages.fr.menu.main]]
  name = "Labs & Writeups"
  pageRef = "#"   
  weight = 4

  [[languages.fr.menu.main]]
  identifier = "labs-root"
  name = "Labs & Writeups"
  pageRef = "labs"
  weight = 5

    [[languages.fr.menu.main]]
    parent = "labs-root"
    name = "CTF's Writeups"
    pageRef = "labs/ctfs"
    weight = 41

    [[languages.fr.menu.main]]
    parent = "labs-root"
    name = "Admin Système"
    pageRef = "labs/sysadmin"
    weight = 42

    [[languages.fr.menu.main]]
    parent = "labs-root"
    name = "Virtualisation"
    pageRef = "labs/virtualization"
    weight = 43

    [[languages.fr.menu.main]]
    parent = "labs-root"
    name = "Réseau"
    pageRef = "labs/networking"
    weight = 44


## Menus EN
[languages.en.menu]

  [[languages.en.menu.main]]
  name = "Home"
  pageRef = "/"          # racine EN
  weight = 1

  [[languages.en.menu.main]]
  name = "About"
  pageRef = "about"      # content/en/about.md
  weight = 2

  [[languages.en.menu.main]]
  name = "Contact"
  pageRef = "contact"
  weight = 3

  [[languages.en.menu.main]]
  name = "Labs & Writeups"
  pageRef = "#"
  weight = 4

  [[languages.en.menu.main]]
  identifier = "labs-root"
  name = "Labs & Writeups"
  pageRef = "labs"
  weight = 5

    [[languages.en.menu.main]]
    parent = "labs-root"
    name = "CTF Writeups"
    pageRef = "labs/ctfs"
    weight = 41

    [[languages.en.menu.main]]
    parent = "labs-root"
    name = "Sys Admin"
    pageRef = "labs/sysadmin"
    weight = 42

    [[languages.en.menu.main]]
    parent = "labs-root"
    name = "Virtualization"
    pageRef = "labs/virtualization"
    weight = 43

    [[languages.en.menu.main]]
    parent = "labs-root"
    name = "Networking"
    pageRef = "labs/networking"
    weight = 44